# docker-compose.yml
version: '3'
networks:
  myapp-network:
services:
  # main application
  myapp:
    container_name: myapp
    build:
      .
    depends_on:
      - "myapp-redis"
    networks:
      - myapp-network
    ports:
      - "8000:8000"
  # service for collecting (dummy) sensor data
  myapp-sensor:
    container_name: myapp-sensor
    build:
      context: .
      dockerfile: ./sensors/Dockerfile
    depends_on:
      - "myapp-redis"
    networks:
      - myapp-network
  # redis cache for storing data
  myapp-redis:
    container_name: myapp-redis
    image: redis
    networks:
      - myapp-network
    expose:
      - "6379"